export const guide = [
      {
        text: '指引',
        items: [
          { text: '文档说明', link: '/guide/intro' },
          { text: '为什么选择我们 ?', link: '/guide/why' },
        ],
        collapsed: true,
      },
      {
        text: '入门',
        items: [
          { text: '准备工作', link: '/guide/ready' },
          { text: '开始', link: '/guide/start' },
          { text: '代码规范', link: '/guide/coding-standard' },
          { text: '术语', link: '/guide/term' },
          { text: '配置', link: '/guide/configure' },
          { text: '路由（导航）', link: '/guide/router' },
          { text: '与服务端交互', link: '/guide/axios' },
          { text: '全局状态管理', link: '/guide/store' },
          { text: '全局资源', link: '/guide/global-resources' },
          { text: '图标', link: '/guide/svg-icon' },
          { text: '构建与预览', link: '/guide/build' },
        ],
        collapsed: false,
      },
      {
        text: '进阶',
        items: [
          { text: '登录', link: '/guide/login' },
          { text: '权限', link: '/guide/permission' },
          { text: '主页', link: '/guide/home' },
          { text: '布局', link: '/guide/layout' },
          { text: '主题', link: '/guide/theme' },
          { text: '动态标题', link: '/guide/title' },
          { text: '导航菜单', link: '/guide/menu' },
          { text: '顶栏', link: '/guide/topbar' },
          { text: '标签栏', link: '/guide/tabbar' },
          { text: '工具栏', link: '/guide/toolbar' },
          { text: '收藏夹', link: '/guide/favorites' },
          { text: '面包屑导航', link: '/guide/breadcrumb' },
          { text: '快捷键', link: '/guide/hotkeys' },
          { text: '版权信息', link: '/guide/copyright' },
        ],
        collapsed: false,
      },
      {
        text: '高级',
        items: [
          { text: '页面缓存', link: '/guide/keep-alive' },
          { text: '国际化', link: '/guide/i18n' },
          { text: '代码文件自动生成', link: '/guide/plop' },
          { text: '标准模块', link: '/guide/plop-module' },
          { text: '常用 API', link: '/guide/api' },
          { text: '私有 Storage 数据', link: '/guide/storage' },
          { text: '页面水印', link: '/guide/watermark' },
          { text: '错误日志', link: '/guide/error-log' },
          { text: '自定义字体', link: '/guide/font' },
          { text: '用户偏好设置', link: '/guide/preferences' },
          { text: 'JSX', link: '/guide/jsx' },
          { text: '基于文件系统的路由', link: '/guide/file-system-route' },
          { text: '使用 Composition API 开发', link: '/guide/vue3-composition-api' },
          { text: '高级 position:fixed', link: '/guide/position-fixed' },
        ],
        collapsed: false,
      },
      {
        text: '其它',
        items: [
          { text: '框架更新', link: '/guide/upgrade' },
          { text: '从 Vue2 版本迁移', link: '/guide/vue2-to-vue3' },
          { text: '从 vue-element-admin 迁移', link: '/guide/vea-to-fa' },
          { text: '常见问题', link: '/guide/q-a' },
        ],
        collapsed: false,
      },
    ]